"use client";

import { useState, useCallback, useEffect } from "react";
import type { Conversation, ConversationMessage, Artifact } from "@/types/database";

/**
 * useChat
 * Manages conversation list, active conversation, messages, and message sending.
 * The primary state hook for the Chat view.
 */
export function useChat() {
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [activeConversation, setActiveConversation] = useState<Conversation | null>(null);
  const [messages, setMessages] = useState<ConversationMessage[]>([]);
  const [artifacts, setArtifacts] = useState<Artifact[]>([]);
  const [isLoadingConversations, setIsLoadingConversations] = useState(true);
  const [isLoadingMessages, setIsLoadingMessages] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [createError, setCreateError] = useState<string | null>(null);

  // Load conversations on mount
  useEffect(() => {
    async function loadConversations() {
      try {
        const res = await fetch("/api/conversations?sort_by=updated_at&sort_order=desc");
        const json = await res.json();
        if (json.data) {
          setConversations(json.data.items);
          // Auto-select the most recent conversation
          if (json.data.items.length > 0 && !activeConversation) {
            setActiveConversation(json.data.items[0]);
          }
        }
      } finally {
        setIsLoadingConversations(false);
      }
    }
    loadConversations();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Load messages when active conversation changes
  useEffect(() => {
    if (!activeConversation) return;

    async function loadMessages() {
      setIsLoadingMessages(true);
      setMessages([]);
      try {
        const res = await fetch(`/api/conversations/${activeConversation!.id}/messages`);
        const json = await res.json();
        if (json.data) {
          setMessages(json.data.items);
        }
      } finally {
        setIsLoadingMessages(false);
      }
    }

    loadMessages();
  }, [activeConversation]);

  const selectConversation = useCallback((id: string) => {
    const conv = conversations.find((c) => c.id === id) ?? null;
    setActiveConversation(conv);
  }, [conversations]);

  const createConversation = useCallback(async () => {
    setCreateError(null);
    const res = await fetch("/api/conversations", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ type: "general" }),
    });
    const json = await res.json();
    if (json.data) {
      setConversations((prev) => [json.data, ...prev]);
      setActiveConversation(json.data);
      setMessages([]);
    } else if (json.error) {
      setCreateError(json.error.message ?? "Failed to create conversation");
    }
  }, []);

  const sendMessage = useCallback(async (content: string) => {
    if (!activeConversation || isSending) return;

    setIsSending(true);

    // Optimistically add user message
    const tempUserMsg: ConversationMessage = {
      id: `temp-${Date.now()}`,
      conversation_id: activeConversation.id,
      created_at: new Date().toISOString(),
      role: "user",
      content,
      artifacts_generated: [],
    };
    setMessages((prev) => [...prev, tempUserMsg]);

    try {
      const res = await fetch(
        `/api/conversations/${activeConversation.id}/messages`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ content }),
        }
      );
      const json = await res.json();
      if (json.data) {
        // Replace temp message with real user message + add agent response
        setMessages((prev) => [
          ...prev.filter((m) => m.id !== tempUserMsg.id),
          json.data.user_message,
          json.data.agent_message,
        ]);
        // Accumulate any artifacts created in this message exchange
        if (json.data.artifacts_created.length > 0) {
          setArtifacts((prev) => [...prev, ...json.data.artifacts_created]);
        }
        // Update conversation updated_at in sidebar
        setConversations((prev) =>
          prev.map((c) =>
            c.id === activeConversation.id
              ? { ...c, updated_at: new Date().toISOString() }
              : c
          )
        );
      }
    } finally {
      setIsSending(false);
    }
  }, [activeConversation, isSending]);

  /**
   * Returns all artifacts that were generated by a specific message.
   * Used by MessageBubble to render inline artifact cards.
   */
  const artifactsForMessage = useCallback(
    (messageId: string): Artifact[] => {
      const msg = messages.find((m) => m.id === messageId);
      if (!msg || msg.artifacts_generated.length === 0) return [];
      return artifacts.filter((a) => msg.artifacts_generated.includes(a.id));
    },
    [messages, artifacts]
  );

  return {
    conversations,
    activeConversation,
    messages,
    isLoadingConversations,
    isLoadingMessages,
    isSending,
    createError,
    selectConversation,
    createConversation,
    sendMessage,
    artifactsForMessage,
  };
}
