/**
 * artifacts.ts
 * Typed content structures for all 6 artifact types.
 * Each interface corresponds to the JSON stored in Artifacts.content.
 *
 * Design decision: content structures are kept separate from the Artifact
 * row type so they can be imported independently by generation/display code
 * without pulling in the full DB type.
 */

// ---------------------------------------------------------------------------
// 1. connection_note
// LinkedIn connection request — hard 300-character limit.
// ---------------------------------------------------------------------------

export interface ConnectionNoteContent {
  /** The final connection request message text */
  message: string;
  /**
   * The "hook" angle used — e.g. "shared INSEAD background".
   * Stored for outcome learning (which hooks get accepted?).
   */
  hook: string;
  /** Actual character count — validated against LinkedIn's 300-char limit */
  char_count: number;
}

// ---------------------------------------------------------------------------
// 2. outreach_draft
// Longer outreach message (LinkedIn message or email).
// ---------------------------------------------------------------------------

export type OutreachChannel = "linkedin_message" | "email";
export type OutreachTone = "professional" | "warm" | "casual";

export interface OutreachDraftContent {
  /** The full message body */
  message: string;
  tone: OutreachTone;
  /** Primary hook angle used in this draft */
  hook: string;
  channel: OutreachChannel;
  char_count: number;
  /**
   * Optional: subject line for email drafts.
   * Not applicable for LinkedIn messages.
   */
  subject?: string;
}

// ---------------------------------------------------------------------------
// 3. meeting_prep
// Pre-meeting briefing combining person summary, company intel, questions,
// and strategic coaching. The most complex artifact type.
// See PRD Feature 4.
// ---------------------------------------------------------------------------

export interface CompanyIntel {
  /** One-paragraph description of what the company does */
  description: string;
  /** Key recent news items (funding, leadership, product, etc.) */
  recent_news: Array<{
    headline: string;
    date?: string;
    source?: string;
  }>;
  /** Top 2-3 strategic priorities or themes for the company */
  strategic_priorities: string[];
}

export interface DiscussionTheme {
  /** Theme label e.g. "Their career transition" */
  name: string;
  /** 2-4 specific questions under this theme */
  questions: string[];
}

export interface MeetingCoaching {
  /** Things to proactively do in the meeting */
  do_list: string[];
  /** Things to avoid */
  dont_list: string[];
  /** How to position yourself given this person's background/interests */
  positioning_advice: string;
  /**
   * Specific ask recommendation: "advice" | "referral" | "introduction" | "none yet"
   * Based on relationship stage — don't ask for referral on a first call.
   */
  recommended_ask: "advice" | "referral" | "introduction" | "none yet";
}

export interface MeetingPrepContent {
  /**
   * 2-3 paragraph summary of the contact:
   * career trajectory, education, key highlights, previous interactions.
   */
  person_summary: string;
  company_intel: CompanyIntel;
  /**
   * Discussion themes with specific questions.
   * Typically 2-3 themes, each with 2-4 questions.
   * See PRD PREP-05.
   */
  discussion_themes: DiscussionTheme[];
  coaching: MeetingCoaching;
  /**
   * Estimated meeting duration in minutes — affects briefing depth.
   * See PRD PREP-06.
   */
  meeting_duration_minutes?: number;
}

// ---------------------------------------------------------------------------
// 4. meeting_notes
// Post-meeting notes captured by the user, structured by the agent.
// ---------------------------------------------------------------------------

export interface MeetingNotesContent {
  /** Bullet-point key takeaways extracted/structured from user's raw notes */
  key_takeaways: string[];
  /**
   * Concrete next steps identified from the meeting.
   * Agent populates from context; user can edit.
   */
  next_steps: Array<{
    description: string;
    /** Relative timing e.g. "within 24 hours", "in 3 weeks" */
    timing: string;
    completed: boolean;
  }>;
  /** The user's original free-text input — preserved verbatim */
  user_raw_notes: string;
  /** ISO date string for when the meeting occurred */
  meeting_date?: string;
}

// ---------------------------------------------------------------------------
// 5. action_plan
// Suggested next actions after a meeting or key milestone.
// Generated by the relationship progression coach. See PRD Feature 6.
// ---------------------------------------------------------------------------

export type ActionPriority = "high" | "medium" | "low";

export interface ActionPlanContent {
  actions: Array<{
    description: string;
    /**
     * Timing guidance: absolute date OR relative string.
     * e.g. "2026-06-15" | "within 24 hours" | "in 3 weeks"
     */
    timing: string;
    priority: ActionPriority;
    completed: boolean;
    /**
     * If this action involves sending a message, a draft may be
     * attached here as a string for quick access.
     */
    draft?: string;
  }>;
  /**
   * Agent's contextual coaching note for this action plan.
   * e.g. "Don't ask for a referral yet — focus on providing value first."
   */
  coaching_note: string;
}

// ---------------------------------------------------------------------------
// 6. follow_up_draft
// Follow-up message drafted after a meeting or interaction.
// Must reference actual conversation context. See PRD REL-02.
// ---------------------------------------------------------------------------

export interface FollowUpDraftContent {
  message: string;
  /**
   * The specific meeting/conversation detail this follow-up references.
   * Ensures the message feels like a natural continuation, not a cold restart.
   */
  reference_to_meeting: string;
  /**
   * Agent's recommendation for when to send this.
   * e.g. "within 24 hours", "in 3 weeks when Q2 hiring cycle starts"
   */
  timing_suggestion: string;
  channel: OutreachChannel;
  tone: OutreachTone;
}

// ---------------------------------------------------------------------------
// Union type mapping ArtifactType → content interface
// ---------------------------------------------------------------------------

export interface ArtifactContentMap {
  connection_note: ConnectionNoteContent;
  outreach_draft: OutreachDraftContent;
  meeting_prep: MeetingPrepContent;
  meeting_notes: MeetingNotesContent;
  action_plan: ActionPlanContent;
  follow_up_draft: FollowUpDraftContent;
}

/** Strongly typed artifact content for a given type T */
export type ArtifactContent<T extends keyof ArtifactContentMap> =
  ArtifactContentMap[T];

/**
 * Union of all valid artifact type strings.
 * Derived from ArtifactContentMap so it stays in sync automatically.
 */
export type ArtifactType = keyof ArtifactContentMap;
